#!/usr/bin/env bash

set -eo pipefail

cleanup() {
	rm -rf "out"
	[ -f "$dex_file" ] && rm "$dex_file"
	return 0
}

main() {
	local file="$1"
	local wd=$(dirname $(realpath $0))

	local lib_dir="$wd/lib"
	local dex_file="classes.dex"

	trap cleanup EXIT

	if [ ! -f "$file" ]; then
		echo "$file not exist!"
		exit 1
	fi

	# Compile Java source file
	javac -classpath "$lib_dir/android/*:$lib_dir/androidx/*" -d "out" "$file"

	# Convert class files to DEX
	"$wd/d8" out/*.class

	# Disassemble DEX to smali
	java -jar "$lib_dir/baksmali.jar" d "$dex_file"

	# Print smali files with colorized headers
	for smali in $(find out -name "*.smali"); do
		echo "\033[36m----- $(basename $smali) -----\033[0m"
		echo
		cat "$smali"
		echo
	done

	cleanup

	exit 0
}

main "$1"
